FC = rose-compiler
FFLAGS = -ffree-line-length-none -fno-range-check -fdefault-real-8
FFLAGS += -rose:plugin_lib /root/precimonious-w-rose/plugins/ProsePlugin.so -rose:plugin_action prose-generate-graph -rose:plugin_arg_prose-generate-graph ./
FFLAGS += -rose:skip_syntax_check
FFLAGS += -rose:skipfinalCompileStep

default: main

main: main.f90 auxiliary_type target_module
	$(FC) $(FFLAGS) -o main main.f90 target_module.o auxiliary_module.o 

target_module: target_module.f90 auxiliary_module
	$(FC) $(FFLAGS) -c target_module.f90

auxiliary_module: auxiliary_module.f90
	$(FC) $(FFLAGS) -c auxiliary_module.f90

auxiliary_type: auxiliary_type.f90
	$(FC) $(FFLAGS) -c auxiliary_type.f90

clean:
	rm -rf *.mod *.o main prose_logs preprocessed_* initial_config.txt *.rmod