FC = rose-compiler
FFLAGS = -ffree-line-length-none -fno-range-check
FFLAGS += -rose:plugin_lib /glade/u/home/jdvanover/precimonious-w-rose/plugins/ProsePlugin.so -rose:plugin_action prose-generate-graph -rose:plugin_arg_prose-generate-graph ./
FFLAGS += -rose:skip_syntax_check
FFLAGS += -rose:skipfinalCompileStep

default: main

main: main.F90 aux_module target_module
	$(FC) $(FFLAGS) -o main main.F90 target_module.o aux_module.o

aux_module: aux_module.f90
	$(FC) $(FFLAGS) -c aux_module.f90

target_module: target_module.f90
	$(FC) $(FFLAGS) -c target_module.f90

clean:
	rm -rf *.mod *.o main prose_logs preprocessed_* initial_config.txt *.rmod rose* prose_workspace

